"""运行时注入的英文字段取值规则；中文对照见 field_value_prompt_rules_cn.py。"""

FIELD_VALUE_SEMANTICS = (
    "[Field-value contract]\n"
    "implementationDescription is the optional endpoint-level mapping description. Implement its confirmed "
    "business validation, execution order, branching, and response handling in the appropriate task stages. "
    "An absent or blank description adds no requirements. It does not authorize additional data sources or "
    "override the API contract, structured mappings, or source snapshots; report conflicts as contract_mismatch.\n"
    "sourceBinding identifies the selected table or external Operation. Even when externalApiBindings is empty "
    "and every response field is value_mapping, retain that source and perform the confirmed upstream call. "
    "Multiple dependencies within one source do not authorize another source, JOIN, or additional call. "
    "Use confirmed sourceSnapshots for physical metadata; never infer mappings solely from equal field names.\n"
    "Read the complete databaseQuery.items tree, databaseWrites, externalApiBindings, and fieldMappings. "
    "databaseQuery governs predicate targets and values; databaseWrites governs write columns and values; "
    "externalApiBindings governs external request targets and values. right.kind=endpoint reads the exact "
    "request location/path; fixed preserves the value and its type; business implements businessDescription "
    "using endpointFields and builtinFields. origin is an editor category, not a runtime algorithm. "
    "One request parameter may feed multiple targets.\n"
    "Implement business_description validation or branching without inventing physical bindings; "
    "value_mapping requires no sourceFields. Process source_mapping after source results are available: "
    "direct is a direct assignment; single_field_description / multi_field_description executes "
    "businessDescription using all declared sourceFields, endpointFields, and builtinFields. Preserve array "
    "item correspondence; do not flatten arrays or select only the first item unless explicitly required.\n"
    "Missing is distinct from false, zero, an empty query result, or an upstream failure. The confirmed rule "
    "and field constraints determine whether an empty string or null is missing. missingBehavior=error "
    "fails according to the confirmed error contract; omit leaves the target absent or removes the predicate; "
    "default uses the typed defaultValue. When a rule explicitly permits a missing dependency and specifies "
    "a branch, execute that branch; do not short-circuit every null dependency into an error. Apply "
    "missingBehavior to other missing required inputs not handled by that rule. Treat invalid input separately "
    "from missing input; never hide validation failures with a default. Never omit required external parameters "
    "or required response fields, or treat upstream timeouts/errors as missing input. Report a concrete "
    "contract gap when essential algorithms, time zones, rounding, or error semantics are absent; do not guess."
)

FIELD_VALUE_PLANNING_RULES = (
    FIELD_VALUE_SEMANTICS,
    "[Field-value task planning] In each applicable Task's numbered Simplified Chinese execution steps, "
    "identify the target location/path or column, input dependencies, processing rule, missing policy, and "
    "pre-call or post-call phase. Do not merely say 'implement field mappings'. Keep the manifest's fixed "
    "Task count: no per-field Task, standalone mapping Task, or new deliverable kind. objects owns shared "
    "typed boundaries; repository owns parameterized access and AND/OR structure; upstream owns transport "
    "DTOs, request sections, and response shapes; service owns business values and response composition; "
    "controller owns HTTP binding and delegation. service computes databaseQuery right values, "
    "databaseWrites, and externalApiBindings before access and passes typed values with explicit presence "
    "to the access layer. Plan matching signatures and necessary value objects together within existing "
    "responsible stages and authorized paths; never require one execution Task to modify another stage's "
    "files outside its scope. Retain upstream responsibility for sourceBinding-only operations. Explicitly "
    "require rejecting update/delete when omit removes all effective predicates. Describe boundary behavior "
    "in implementation steps without adding test, build, or acceptance Tasks.",
)

FIELD_VALUE_IMPLEMENTATION_RULES = (
    FIELD_VALUE_SEMANTICS + "\n\n"
    "[Field-value execution order] Apply only the current stage's responsibilities. service first validates "
    "business inputs and resolves trusted server context, computes pre-call query/write/upstream values, "
    "invokes the planned Repository / Client, then constructs the internal response. current_user_id comes "
    "from the authenticated server principal and current_time from the server clock. When context is "
    "unavailable, obey the missing policy; never trust client-supplied identity. Never construct a call's "
    "request using its not-yet-available response. Preserve false/zero and explicitly distinguish absence "
    "from a target whose value is null.\n"
    "repository consumes resolved typed values and preserves AND/OR parentheses, repeated columns, and "
    "reused parameters. Remove empty groups after omit, but never replace them with always-true predicates. "
    "Reject update/delete when no effective predicate remains. Parameterize every value. Use parameterized "
    "LIKE with wildcard escaping for contains/starts_with/ends_with; require non-empty IN arrays and "
    "ordered two-value BETWEEN arrays. upstream binds resolved values into the exact "
    "path/query/header/request_body sections. omit means not sending the target, not substituting a literal "
    "null string or empty string. Do not repeat business rules in Client, Mapper, or Controller.\n"
    "Implement confirmed rules as ordinary typed Java code, never as eval, a script engine, or a new runtime "
    "LLM call. Missing required semantics returns failed with failure_category=contract_mismatch; missing "
    "planned type boundaries or write authorization returns failed with failure_category=plan_mismatch. "
    "Both require a concrete change_request; never expand the write scope yourself.\n\n"
)
